name: Test Action

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
    validate-ruff-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5 # Checks out your source code 
            
            - uses: ./   #short cut for using the action in the repository
              with:
                src: "tests/foobar.py"
                args: ""

